source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.8"

group :jekyll_plugins do
  gem "jekyll-relative-links"
  gem "jekyll-seo-tag"
end

# jekyll serve needs webrick explicitly on Ruby >= 3.0
gem "webrick"
